name: Finalize Release Version

on:
  pull_request:
    branches:
      - main

jobs:
  finalize-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Extract version from branch name
        id: extract_version
        run: |
          BRANCH_NAME=$(echo ${{ github.event.pull_request.head.ref }} | sed 's/^release\///')
          echo "::set-output name=version::$BRANCH_NAME"

      - name: Update project version to final release
        run: mvn versions:set -DnewVersion=${{ steps.extract_version.outputs.version }}

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add pom.xml
          git commit -m "Finalize project version to ${{ steps.extract_version.outputs.version }}"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}